server:
  port: 8080
  servlet:
    context-path: /test
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
xcauth:
  interceptor:
    excludePath: /login/**;/logout/**;/error;
    includePath: /**
    refreshGap: 30
  jwt:
    privateKey: a1346792580
    ttl: 30

